// 刘佳豪/第一阶段/Js/React/React05/my-app/src/Cart.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
export default class Cart extends Component {
  constructor(props) {
    super(props);
    console.log(props);
  }
  render() {
    return (
      <div>
        <div className="container-fluid">
          <h2>我的购物车</h2>
          <div className="alert alert-warning" role="alert">
            <Link to={"/product"}>点击返回商品列表</Link>
          </div>
          {/* 购物车列表 */}
          <table className="table table-striped">
            <thead>
              <tr>
                <th>商品名称</th>
                <th>单价</th>
                <th>数量</th>
                <th>小计</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
              {this.props.a.map((v, i) => {
                return (
                  <tr key={i}>
                    <td>{v.name}</td>
                    <td>{v.price}</td>
                    <td>{v.count}</td>
                    <td>{v.price * v.count}</td>
                    <td>
                      <button className="btn btn-danger">删除</button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    );
  }
}

// 刘佳豪/第一阶段/Js/Vue07/vue07/src/components/Cart.vue
<template>
	<div class="container-fluid">
		<h2>购物车</h2>
		<div class="alert alert-warning" role="alert">
			<router-link to="/product">点击返回商品列表</router-link>
			<table class="table table-striped">
				<thead>
					<td>商品名称</td>
					<td>单价</td>
					<td>数量</td>
					<td>小计</td>
					<td>操作</td>
				</thead>
				<tbody>
					<tr v-for="(pro,i) in c">
						<td>{{pro.name}}</td>
						<td>{{pro.price}}</td>
						<td>{{pro.count}}</td>
						<td>{{pro.count*pro.price}}</td>
						<td><button class="btn btn-danger" @click="del(pro,i)">删除</button></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</template>

<script>
	export default {
		name: "Cart",
		data() {
			return {
				cartPros: [],
				c: []
			}
		},
		created() {
			this.cartPros = this.$parent.sendCartPros();
			this.axios.get("/cart", {}).then(data => {
				this.c = data
			}).catch(err => {
				console.log(err)
			})
		},
		methods: {
			del(i, v) {
				this.axios.get("/delete", {
					params: {
						name: i.name,
						price: i.price,
						count: 1
					}
				}).then(this.axios.get("/cart", {}).then(data => {
					this.c = data
					console.log(this.c)
				})).catch(err => {
					console.log(err)
				})
			},
		},
	}
</script>

<style scoped>

</style>
